### ISSUE TITLE
Typescript ESLint is Cranky

### ISSUE THREAD

**Issue by jherdman** [alexlafroscia/qunit-wait-for#146]
I have a Typescript codebase configured with typescript-eslint. It's showing the following error:

<img width="931" alt="Screen Shot 2021-10-26 at 3 31 58 PM" src="https://user-images.githubusercontent.com/3300/138948317-1c88d004-2b5f-4765-b7bd-83876f50385d.png">

How does one resolve this?

**Comment by alexlafroscia** [comment]
No problem
