### ISSUE TITLE
Assertions in async code outside of callback break

### ISSUE THREAD

**Issue by lukemelia** [alexlafroscia/qunit-wait-for#16]
I ran into a situation where my test has an `assert.waitFor` as well as a mirage.js handler that is triggered after the assert.waitFor starts but before it is successful. Within my mirage handler, I have a regular qunit assertion about the mirage request. When this assertion runs successfully, there is an error. I suspect it has to do with something assert.waitFor is doing.

Hopefully, that info is helpful enough to diagnose and address the issue. If not, let me know.

Thanks for the useful tool!

**Comment by alexlafroscia** [comment]
> I suspect it has to do with something assert.waitFor is doing.

Hmm... that certainly could be. We do some hack-y stuff to override the default implementation of `assert.pushResult` for a period of time and that might mess with some stuff.

From the information you gave, it sounds like the situation is something like this:

```javascript
this.server.get('/whatever', () => {
  assert.ok(true, 'Hit the server');
});

await visit('/some-url');

await assert.waitFor(() => {
  assert.dom('...').exists();
});
```

Is that more-or-less right? The idea being that the server has an assertion that will be valid sometime while the `waitFor` is polling the callback, even though the callback's initial assertions will not be valid.

**Comment by lukemelia** [comment]
@alexlafroscia yes, you've captured the essence of it. Is it possible to only leave the override in place while you are executing the waitFor callback?

**Comment by alexlafroscia** [comment]
If I am understanding you right, that’s how it works now — we only replace `pushResult` at the point that `waitFor` is called, and put the original implementation back when it resolves.

I believe the issue is that the assertion in the Mirage handler is being run in the period while the original is replaced.

I think I _should_ be able to write up a test case based on this discussion and will open a PR with that to verify that the sequence of events looks right. Might need to do something “clever” and detect assertions within the callback vs. ones outside the callback.

**Comment by lukemelia** [comment]
My mental model of how this tool works is that it does the following:

1) Replace pushResult
2) Repeat:
  a) execute callback
  b) if successful, goto 3, else setTimeout for (a), 
3) Restore pushResult

I was thinking it might fix the problem if instead it did it this way::

1) Repeat:
  a) Replace pushResult
  b) execute callback
  c) Restore callback
  d) if successful, we're done, else setTimeout for (a)

I may be over-simplifying though. Your plan to put together a test case is certainly the best next step in any event!

**Comment by alexlafroscia** [comment]
Ahh, yes! I think you're right about that. I'll see if that can resolve the issue!

**Comment by alexlafroscia** [comment]
I added a test and a "fix" here

https://github.com/alexlafroscia/qunit-wait-for/pull/17

The test failed without the fix. Does the test seem to re-create something like the scenario you're facing? I _think_ that usage of `setTimeout` should be close enough to something like what you ran into.

As you mentioned, moving the replacement code to run on each "repeat" and _only_ doing it right before/after the callback is called was a good fix!

**Comment by lukemelia** [comment]
@alexlafroscia yep, looks good to me! Nice work.

I don't know enough about JS runtimes and async/await to feel 100% confident this will solve all problems of this type, but I feel confident that this will solve it for all cases where the waitFor callback is sync, which I imagine covers most if not all of the usage.

**Comment by alexlafroscia** [comment]
I just cut `1.2.1` that contains that PR -- let me know if that doesn't solve your issue!

**Comment by lukemelia** [comment]
@alexlafroscia confirmed fixed! 👍
